# Generated by Django 5.0.1 on 2024-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedresource',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='material name'),
        ),
    ]
