# Generated by Django 5.0.1 on 2024-03-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_blockedresource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedresource',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='url name'),
        ),
    ]
